### ISSUE TITLE
Training Corpus

### ISSUE THREAD

**Issue by benstrumeyer** [cypherix93/nlp-steam-reviews-analysis#13]
Our training corpus is the set of all games except the one we're evaluating. We need a method to train on these games and extract their respective polarities. This will be used to evaluate the test game's reviews.

**Comment by cypherix93** [comment]
Progress Made:
- We are training with the entire data set and saving all the phrases extracted into the "training_phrases" collection.
- At this point, the database has information about all the phrases extracted from all the reviews including the game the review was tied to, and if the review was recommended or not.
- This way we can get all the extracted phrases at one db call and do computations on the fly without training each time.
